const listKampus = [
    "Universitas Riau",
    "Universitas Pelita Harapan Medan",
    "Universitas Indonesia",
    "Universitas Gadjah Mada",
    "Bandung Institute of Technology",
    "Universitas Brawijaya",
    "Universitas Negeri Medan",
    "Universitas Airlangga",
    "Sekolah Tinggi Ekonomi Islam SEBI",
    "University of Kassel and Berlin School of Economic",
    "Institut pertanian bogor",
    "Universitas Negeri Padang",
    "University of Kassel and Berlin School of Economic",
    "Universitas Lampung",
    "universitas lambung mangkurat",
    "Halu Oleo university",
    "Politeknik Elektronika Negeri Surabaya",
    "Institut Perguruan Tinggi Ilmu Al-Qur'an",
    "Universitas Muhammadiyah Yogyakarta",
    "Institut Teknologi Sepuluh Nopember Surabaya",
    "Telkom University",
    "institut agama islam negeri bengkulu",
    "Universitas Sebelas Maret",
    "Universitas Prasetiya Mulya",
    "Universitas Muhammadiyah Prof. Dr. Hamka",
    "Institut Teknologi Indonesia",
    "universitas pembangunan nasional veteran yogyakart",
    "universitas pembangunan nasional veteran yogyakart",
    "universitas pembangunan nasional veteran yogyakart",
    "Universitas Hasanuddin",
    "Universitas Negeri Jakarta",
    "universitas pembangunan nasional veteran yogyakart",
    "universitas pembangunan nasional veteran yogyakart",
    "universitas pembangunan nasional veteran yogyakart",
    "universitas pembangunan nasional veteran yogyakart",
    "universitas pembangunan nasional veteran yogyakart",
    "Universitas Indonesia",
    "STKS Bandung",
    "Uin sunan ampel surabaya",
    "Universitas Negeri Jakarta",
    "Universitas Negeri Padang",
    "Universitas Sunan Gunung Djati Bandung",
    "Politeknik Negeri Semarang",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "Institut Teknologi Bandung",
    "Swiss German University",
    "Universitas Mataram",
    "Universitas Islam Negeri Raden Fatah Palembang",
    "UIN Raden Fatah Palembang",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Padjadjaran",
    "Paramadina University",
    "UIN Walisongo Semarang",
    "Universitas Padjadjaran",
    "Universitas Muhammadiyah Makassar",
    "Universitas Muhammadiyah Mataram",
    "Universitas Brawijaya",
    "Universitas Islam Negeri Sunan Gunung Djati",
    "UIN Sultan Maulana Hasanuddin Banten",
    "Andalas University",
    "UNPAD",
    "Universitas Airlangga",
    "Universitas Jember",
    "President University",
    "Universitas Gadjah Mada",
    "Universitas Kristen Satya Wacana",
    "Universitas Brawijaya",
    "Universitas Lampung",
    "Diponegoro University",
    "Universitas Sumatera Utara",
    "Universitas Sumatera Utara",
    "UIN ALAUDDIN MAKASSAR",
    "Universitas Indonesia",
    "Universitas Sumatera Utara",
    "Pasundan University",
    "Universitas Islam Indonesia",
    "Institut Pertanian Bogor",
    "Universitas Brawijaya",
    "UIN Sunan Gunung Djati Bandung",
    "Poltekkes Kemenkes RI Padang",
    "Universitas islam as-syafi'iyah",
    "Universitas Majalengka",
    "Universitas Sumatera Utara",
    "Universitas Negeri Semarang ",
    "Universitas Gadjah Mada",
    "Sedang proses di Universitas Muhammadiyah Prof. DR",
    "Sedang proses di Universitas Muhammadiyah Prof. DR",
    "Sedang proses di Universitas Muhammadiyah Prof. DR",
    "Universitas Islam Negri Jakarta",
    "Universitas Negeri Medan",
    "University of Sumatera Utara",
    "Universitas Andalas",
    "University of Diponegoro",
    "Andalas University",
    "UIN Sunan Gunung Djati",
    "Universitas Pancasakti Tegal",
    "Universitas Riau",
    "Institut Teknologi Kalimantan",
    "Universitas Negeri Padang",
    "Universitas Diponegoro",
    "Universitas Brawijaya",
    "ITB",
    "Universitas Teknologi Sumbawa",
    "Universitas Tadulako",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Mulawarman",
    "Universitas Islam Negeri Sunan Ampel Surabaya",
    "Universitas Negeri Makassar ",
    "Universitas Sriwijaya ",
    "Politeknik Negeri Jember",
    "Universitas Diponegoro",
    "Universitas Diponegoro",
    "Universitas Tadulako",
    "Universitas bengkulu",
    "Universitas Sultan Syarif Kasim Riau",
    "Universitas Diponogoro",
    "Universitas Sebelas Maret",
    "Universitas Lampung",
    "Universitas Negeri Jakarta",
    "Iain Manado",
    "Institut Kesehatan Indonesia ",
    "Universitas Hasanuddin",
    "Universitas Sriwijaya",
    "Universitas Muhammadiyah Yogyakarta",
    "STIKES Sumatera Utara ",
    "Universitas Islam Negeri Raden Fatah Palembang",
    "UIN Bandung",
    "Institut Teknologi Sepuluh Nopember Surabaya",
    "Institut Agama Islam Negeri Kendari ",
    "Universitas Gadjah Mada",
    "UIN Alauddin Makassar ",
    "Universitas Pendidikan Indonesia",
    "Universitas Gadjah Mada",
    "Universitas Islam Balitar",
    "Fakultas Hukum Universitas Jember",
    "Universitas Indonesia",
    "Universitas Sumatera Utara",
    "Universitas Ahmad Dahlan",
    "UNIVERSITAS NEGERI GORONTALO",
    "Universitas Padjadjaran",
    "Universitas Indraprasta PGRI ",
    "universitas usltan ageng tirtayasa",
    "universitas sultan ageng tirtayasa",
    "Universitas Brawijaya",
    "sriwijaya university",
    "Poltekkes Kemenkes Padan",
    "Institut Pertanian Bogor",
    "Politeknik STTT Bandung ",
    "Universitas negeri Semarang ",
    "Universitas AIrlangga",
    "Institut Teknologi Bandung",
    "Universitas Udayana",
    "Sekolah Tinggi Teknologi Nuklir - Badan Tenaga Nuk",
    "Universitas Brawijaya",
    "Universitas Hasanuddin",
    "Universitas Borneo Tarakan",
    "udayana university",
    "National Taiwan University of Science and Technolo",
    "Universitas Hasanuddin",
    "Institut Pertanian Bogor",
    "Universitas Diponegoro",
    "SMAN 1 BUNGORO",
    "STMIK Triguna Dharma",
    "SMK Farmasi Bhakti Wiyata Kediri",
    "Universitas Riau",
    "UIN Jakarta",
    "Institut Teknologi Padang",
    "Politeknik Manufaktur Negeri Bangka Belitung",
    "Universitas Mercu Buana Jakarta",
    "Politeknik Negeri Sriwijaya",
    "STID Mustafa Ibrahim",
    "institut teknologi bandung",
    "Universitas Putra Indonesia",
    "Universitas Negeri Semarang",
    "National Taiwan University of Science and Tech.",
    "UNIVERSITAS MULAWARMAN",
    "Universitas Gadjah Mada",
    "Binus University",
    "Politeknik Negeri Sriwijaya",
    "Universitas Diponegoro",
    "Universitas Negeri Makassar",
    "Bina Nusantara University",
    "Universitas Negeri Padang",
    "Universitas Pekalongan",
    "Universitas Gunadarma",
    "Universitas Jambi",
    "Sekolah Tinggi Ekonomi Islam Tazkia",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Negeri Semarang",
    "Institut Teknologi Sepuluh Nopember",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Borneo Tarakan",
    "Diponegoro University",
    "Institut Seni Indonesia Surakarta",
    "Universitas Paramadina",
    "Institut Pertanian Bogor",
    "Universitas Indonesia",
    "Universitas Brawijaya",
    "Universitas Islam Negeri Syarif Hidayatullah",
    "Universitas Airlangga",
    "Universitas Negeri Semarang",
    "Universitas borneo tarakan",
    "MH Thamrin University",
    "SMA N 2 Tuban",
    "Universitas Sumatera Utara",
    "Universitas Indonesia",
    "sekolah tinggi teknik PLN",
    "Pai UNISBA",
    "Institut Pernatian Bogor",
    "Universitas Jambi ",
    "IAIN Sultan Amai Gorontalo",
    "Unpad",
    "STKIP Pasundan Cimahi",
    "Institut Ilmu Sosial dan Ilmu Politik",
    "Universitas Brawijaya",
    "Universitas Jember",
    "Institut Teknologi Sepuluh Nopember",
    "UIN Syarif Hidayatullah Jakarta",
    "Politeknik Negeri Bandung",
    "Universitas Muhammadiyah Jakarta",
    "SMA Negeri 1 Trenggalek",
    "UIN JAKARTA",
    "Universitas Sebelas Maret Surakarta",
    "Universitas Surya",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Sultan Ageng Tirtayasa",
    "Universitas Brawijaya",
    "SMK MIGAS CEPU",
    "Universitas Negeri Padang",
    "Universitas Respati Indonesia",
    "Stikubank Semarang University",
    "Universitas Gadjah Mada",
    "UNIVERSITAS DIPONEGORO",
    "Universitas Sriwijaya",
    "Sriwijaua University",
    "Sriwijaya University",
    "STEI Indonesia ",
    "Universitas Padjadjaran",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas gadjah mada",
    "STIKES Bhakti Pertiwi Indonesia",
    "STKIP PGRI BANJARMASIN",
    "Universitas Komputer Indonesia",
    "Universitas Pelita Harapan Surabaya",
    "Univesitas Muhammadiyah Malang",
    "Universitas Sumatera Utara",
    "Universitas Muhammadiyah Malang",
    "Universitas Bengkulu",
    "Telkom University",
    "Institut Pertanian Bogor",
    "Universitas sriwijaya ",
    "Uin Syarif Hidayatullah Jakarta ",
    "Universitas Muslim Nusantara Al-Washliyah (UMNAW)",
    "STIE Putera Perdana Indonesia",
    "UIN Sunan Kalijaga Yogyakarta ",
    "Unpad",
    "Universitas Islam Indonesia",
    "Poltekkes Kemenkes Yogyakarta",
    "Universitas Pendidikan Indonesia",
    "Institut bisnis nusantara",
    "Politeknik Negeri Medan",
    "Politeknik Negeri Media Kreatif Jakarta",
    "uin syarif hidayatullah jakarta",
    "Institut Pertanian Bogor",
    "Sekolah Tinggi Teknologi Nusa Putra",
    "Universitas Mataram",
    "Universitas Lambung Mangkurat",
    "Universitas Sumatera Utara",
    "Universitas PGRI Adi Buana Surabaya",
    "universitas Indonesia",
    "Institut Pertanian Bogor",
    "Universitas Indraprasta PGRI",
    "KAHFI Motivator School",
    "Universitas Jenderal Soedirman",
    "Institut Kesehatan Indonesia",
    "Universitas Sriwijaya",
    "Institut Pertanian Bogor ",
    "Universitas Bengkulu ",
    "Palangka Raya University",
    "Sekolah tinggi ilmu kesehatan sumatera utara",
    "Universitas Indonesia ",
    "Budi Luhur University",
    "Institut Teknologi Sepuluh Nopember Surabaya",
    "Universitas Sultan Syarif Kasim Riau",
    "Politeknik Negeri Semarang",
    "Universitas Pembangunan Nasional Veteran Yogyakart",
    "SMA 2 Painan",
    "Universitas Indonesia",
    "University of Jakarta (UNIJA) ",
    "Universitas Indonesia",
    "Universitas Islam Negeri Raden Fatah",
    "SRIWIJAYA UNIVERSITY",
    "Universitas Pamulang",
    "universitas riau",
    "universitas pendidikan indonesia",
    "universitas riau",
    "IAIN Palangka Raya",
    "UGM",
    "Universitas Padjadjaran",
    "universitas trunojoyo madura",
    "Univeristas Indonesia",
    "Universitas Riau",
    "SMA MTA Surakarta",
    "STIS",
    "Perbanas Institute",
    "Pertamina University",
    "Universitas Pamulang",
    "SMAN 15 Bandung ",
    "Universitas negeri padang",
    "UNIVERSITAS NEGERI MEDAN",
    "Politeknik Elektronika Negeri Surabaya",
    "Universitas Andalas",
    "Universitas Muhammadiyah Prof. DR. Hamka",
    "Universitas tadulako",
    "Institut Pertanian Bogor",
    "Institut Teknologi Bandung",
    "Univ Gadjah Mada",
    "Universitas Dr. Soetomo Surabaya",
    "Universitas Negeri Makassar",
    "Universitas Islam",
    "Universitas Negeri Makassar",
    "Universitas Jambi",
    "Universitas Dian Nuswantoro Semarang",
    "Sintuwu Maroso University",
    "IPB",
    "Universitas Gadjah Mada",
    "ITB",
    "Universitas Islam Indonesia",
    "Universitas Pamulang",
    "SMK Negeri 7 (STM Pembangunan) Semarang",
    "UNJ",
    "SMK Negeri 1 Sawo",
    "UNJ",
    "Universitas Hasanuddin",
    "Politeknik Negeri Semarang",
    "Universitas Halu Oleo",
    "UNIVERSITAS ISLAM NEGERI",
    "Universitas Riau",
    "Institut Agama Islam Negeri Surakarta (IAIN Suraka",
    "IPB",
    "Universitas Gadjah Mada",
    "POLITEKNIK NEGERI MALANG",
    "Diponegoro University",
    "STHukum Garut",
    "Universitas Sumatera Utara",
    "Universitas Padjadjaran",
    "TEKNIK UHAMKA",
    "UIN SUSKA RIAU",
    "Universitas Brawijaya",
    "Universitas Padjadjaran",
    "Institut Teknologi Bandung",
    "Universitas Tadulako",
    "Universitas Hasanuddin",
    "Universitas Ciputra",
    "IAIN Syekh Nurjati Cirebon",
    "UIN Walisongo Semarang",
    "Universitas  Diponegoro",
    "IKIP PGRI PONTIANAK",
    "Universitas Muhammadiyah Yogyakarta",
    "Universitas Islam Negeri Sunan Gunung Djati",
    "Universitas Andalas",
    "UNIVERSITAS JAMBI ",
    "SMA Al JABR",
    "Univesitas Diponegoro",
    "Universitas Jenderal Soedirman",
    "Universitas Pendidikan Indonesia",
    "Universitas Brawijaya",
    "Universitas Nasional",
    "Universitas Lambung Mangkurat",
    "Universitas Nasional",
    "0",
    "o",
    "Airlangga University",
    "Universitas Nasional",
    "SMKN 1 Talaga",
    "Politeknik STMI Jakarta",
    "Universitas Mataram",
    "Universitas Muhammadiyah Tapanuli Selatan",
    "Poltekkes Kemenkes Kaltim",
    "Institut Pertanian Bogor",
    "Universitas Muhammadiyah Malang",
    "Universitas Sumatera Utara",
    "Universitas Negeri Malang",
    "Institut Teknologi Bandung",
    "Universitas Negeri Padang",
    "Universitas Brawijaya",
    "Universitas Hasanuddin ",
    "State University of Malanh",
    "State University of Malang",
    "Universitas Sumatera Utara",
    "Padang State of University",
    "Universitas Jendral Achmad Yani",
    "Politeknik STMI JAKARTA",
    "UPI",
    "Institut Teknologi Bandung",
    "Universitas Sebelas Maret",
    "UIN Sultan Maulana Hasanuddin Banten",
    "Universitas Negeri Surabaya",
    "Tridinanti University",
    "Institut Pertanian Bogor",
    "SMAN 1 WAY JEPARA ",
    "Universitas Sebelas Maret",
    "Universitas Pendidikan Indonesia",
    "Universitas Airlangga",
    "Hasanuddin University",
    "Universitas Trunojoyo Madura",
    "Universitas Tadulako",
    "Universitas Multimedia Nusantara",
    "universitas sriwijaya",
    "Universitas Indonesia",
    "UIN Syarif Hidayathullah Jakarta",
    "universitas negeri semarang",
    "Universitas Indonesia",
    "IAIN Palangka Raya",
    "Universitas Islam Negeri (UIN) Sunan Gunung Djati ",
    "Universitas Indonesia",
    "Universitas Muhammadiyah palembang",
    "Universitas Sumatera Utara",
    "Institut Pertanian Bogor",
    "Lambung Mangkurat University",
    "Universitas negeri padang",
    "Universitas Sebelas Maret",
    "Lampung Uiversity",
    "UPN \"Veteran\" Yogyakarta",
    "Politeknik Negeri Media Kreatif",
    "Universitas Negeri Malang",
    "Universitas Islam Negeri Maulana Malik Ibrahim Mal",
    "STAIN Curup",
    "Institut Pertanian Bogor",
    "Universitas negeri malang",
    "Universitas Pendidikan Indonesia",
    "Universitas Malikussaleh",
    "Universitas Malikussaleh",
    "SMA N 3 Slawi",
    "IFP School (Ecole Nationale Superieure du Petrole ",
    "sdcsd",
    "Universitas Nasional",
    "Universitas Brawijaya",
    "Universitas Muhammadiyah Malang",
    "Universitas Mulawarman",
    "Institut Pertanian Bogor",
    "Universitas Syiah Kuala Teknik Sipil ",
    "Universitas Brawijaya",
    "Surya University",
    "Universitas Padjadjaran",
    "Telkom University",
    "Universitas Jenderal Achmad Yani",
    "SMA Negeri 1 Ketapang",
    "Universitas Sumatera Utara",
    "Universitas Muhammadiyah Malang",
    "SMA Negeri 1 Selong",
    "Universitas Tidar Magelang",
    "Universitas Diponegoro",
    "Sekolah Tinggi Meteorologi Klimatologi dan Geofisi",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Jember",
    "Institut Teknologi Sepuluh Nopember Surabaya",
    "Universitas Gadjah Mada",
    "Hasanuddin University",
    "Universitas Pendidikan Indonesia",
    "Universitas Andalas",
    "Universitas Brawijaya",
    "UIN Walisongo Semarang",
    "IAIN Bukittinggi",
    "Udayana University",
    "Sriwijaya University",
    "Universitas Brawijaya Malang",
    "IAIN Bukittinggi",
    "Universitas Halu Oleo",
    "Institut Teknologi Bandung",
    "Institut Teknologi Bandung",
    "STAINU Jakarta",
    "Universitas Islam Negri Sunan Gunung Djati Bandung",
    "UIN Sunan Gunung Djati Bandung",
    "LIPIA Jakarta",
    "Universitas Lampung",
    "Universitas Negeri Padang",
    "Universitas Indonesia",
    "universitas internasional semen indonesia",
    "IPB",
    "Universitas Islam Negeri Maulana Malik Ibrahim Mal",
    "BINUS University",
    "Universitas Bengkulu",
    "Universitas Widyatama Bandung",
    "Politeknik Negeri Sriwijaya",
    "Universitas Sultan Ageng Tirtayasa",
    "Institut Teknologi Sumatera",
    "STIE INDONESIA RAWAMANGUN",
    "Institut Teknologi Sepuluh nopember",
    "Institut Pertanian Bogor",
    "Institut Teknologi Kalimantan",
    "Universitas Airlangga ",
    "Universitas Gadjah Mada",
    "UIN Syarif Hidayatulah Jakarta",
    "Universitas Muhammadiyah Malang ",
    "Universitas Multimedia Nusantara ",
    "Universitas Syiah Kuala",
    "Institut Pertanian Bogor",
    "AMIK SERANg",
    "Universitas Islam Indonesia",
    "University of Jember",
    "Universitas Padjadjaran",
    "Universitas Sriwijaya",
    "Institut Pertanian Bogor",
    "UNIVERSITAS PADJADJARAN",
    "Unicersitas Sebelas Maret",
    "Universitas Gadjah Mada",
    "Sekolah Tinggi Meteorologi Klimatologi dan Geofisi",
    "Makassar Of University",
    "Universitas Islam Negeri Walisongo Semarang",
    "STT MIGAS",
    "Universitas Trisakti",
    "Poltekkes Surakarta",
    "Universitas Pendidikan Indonesia",
    "Sekolah Tinggi Ilmu Statistik",
    "Universitas Bengkulu",
    "IPB",
    "Universitas Negeri Semarang",
    "universitas malikussaleh",
    "Universitas Bung Karno",
    "SMA N 1 Abiansemal",
    "Universitas Syiah Kuala",
    "Institut Koperasi Indonesia (IKOPIN)",
    "Universitas Negeri Surabaya",
    "Universitas Sriwijaya ",
    "IAIN Salatiga",
    "Universitas Airlangga",
    "Its",
    "Universitas Syiah Kuala",
    "Universitas Diponegoro",
    "universitas muhammadiyah sumatera utara",
    "Politeknik Elektronika Negeri Surabaya",
    "Universitas Esa Unggul",
    "S1-Matematika",
    "S1-Matematika Undip",
    "UIN Syarif Hidayatullah Jakarta",
    "Univesitas Hasanuddin",
    "Universitas Tanjungpura Pontianak",
    "Universitas Indonesia",
    "Universitas Islam Negeri Ar-Raniry",
    "Universitas Ibnu Khaldun Bogor",
    "Universitas Brawijaya",
    "Universitas Padjadjaran",
    "iain purwokerto",
    "universtitas islam negeri sultan syarif kasim riau",
    "Universitas mulawarman",
    "ITS Surabaya",
    "Universitas Indonesia",
    "Universitas Riau Kepulauan",
    "universitas sultan ageng tirtayasa",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Bengkulu",
    "Telkom University",
    "Universitas Sumatera Utara",
    "Universitas muslim indonesia",
    "STMIK Nusamandiri Jakarta",
    "Universitas Sriwijaya ",
    "Institut Pertanian Bogor",
    "universitas airlangga",
    "Universitas Syiah Kuala",
    "Institut Agama Islam Negeri Purwokerto",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Internasional Batam",
    "Program Magister ITB Bandung",
    "Universitas Garut",
    "universitas malikussaleh",
    "STIE INDONESIA",
    "MA ALI MAKSUM JOGJAKARTA",
    "Universitas Muhammadiyah Jakarta",
    "Universitas Gadjah Mada",
    "Universitas Indonesia",
    "Universitas negeri makassar",
    "Universitas Andalas",
    "Universitas Sriwijaya",
    "Universitas Jambi ",
    "Tadulako University ",
    "UIN Sunan Gunung Djati Bandung",
    "Universitas Negeri Malang",
    "Universitas Diponegoro",
    "Universitas Jenderal Achmad Yani",
    "Universitas samudra",
    "Andalas University",
    "Universitas Maritim Raja Ali Haji",
    "IAIN BUKITTINGGI",
    "Universitas Muhammadiyah Makassar",
    "Man linggo sari baganti",
    "Universitas Riau",
    "UNIVERSITAS LAMBUNG MANGKURAT",
    "Institut Teknologi Bandung",
    "Uin Raden Fatah Palembang ",
    "Universitas Malikussaleh",
    "Universitas Islam Negeri Alauddin Makassar",
    "Universitas Gadjah Mada",
    "Universitas Lampung",
    "Universitas Islam Negeri Sumatera Utara ",
    "UIN Antasari Banjarmasin",
    "Universitas Mulawarman",
    "Diponegoro University",
    "Politeknik Negeri Cilacap ",
    "Institut Teknologi Sepuluh Nopember",
    "Tidar University",
    "Brawijaya University",
    "Airlangga University",
    "Universitas Sulawesi Barat",
    "Universitas Andalas Fakultas Kedokteran Universita",
    "Universitas Mulawarman",
    "Universitas Diponegoro",
    "Universitas Sriwijaya",
    "Universitas Islam Indonesia",
    "Universitas Gadjah Mada",
    "LSPR Jakarta",
    "UNIVERSITAS INDONESIA",
    "STAI Hubbulwathan Duri",
    "Universitas Riau",
    "Politeknik Negeri Jakarta",
    "STEI Tazkia",
    "Universitas Pendidikan Indonesia",
    "IAIN Raden Fatah Palembang ",
    "Politeknik Negeri Jember",
    "THE NATIONAL UNIVERSITY OF MALAYSIA & UNIVERSITY O",
    "Universitas Negeri Malang",
    "Poltekkes Surakarta",
    "Universitas Trunojoyo Madura ",
    "Sekolah Tinggi Kesejahteraan Sosial Bandung",
    "Universitas Islam Sultan Agung",
    "universitas islam negeri alauddin makassar",
    "Universitas Indonesia",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Negeri Malang",
    "Universitas Negeri Makassar ",
    "Universitas Diponegoro",
    "Universitas Padjadjaran",
    "Politeknik Elektronika Negeri Surabaya",
    "Universitas Muhammadiyah Yogyakarta",
    "Universitas Sebelas Maret Surakarta",
    "Sma negeri 15 palembang",
    "Universitas Brawijaya",
    "Politeknik Negeri Media Kreatif",
    "UGM",
    "Institut Teknologi Bandung",
    "UIN Alauddin Makassar",
    "UNIVERSITAS NEGERI MAKASSAR",
    "universitas negeri makassar S1 teknologi pendidika",
    "universitas negeri makassar S1 teknologi pendidika",
    "Universitas Muhammadiyah Makassar",
    "Syarif Hidayatullah State Islamic University",
    "Universitas Tadulako",
    "Poltekkes Kemenkes Yogyakarta",
    "SMP Plus Imam Syafi'i",
    "SMK Negeri 1 Cimahi",
    "Universitas Jember",
    "Universitas Andalas Fakultas Kedokteran Prodi Pend",
    "Universitas Andalas Pendidikan Dokter",
    "Universitas Brawijaya",
    "Universitas Muhammadiyah makassar",
    "Universitas Syiah Kuala",
    "Universitas Lampung",
    "Institut Pertanian Bogor",
    "Universitas Muhammadiyah Makassar",
    "universitas malikussaleh",
    "UIN Sunan Gunung Djati Bandung",
    "POLITEKNIK PARIWISATA PALEMBANG",
    "University of Edinburgh",
    "Universitas Brawijaya",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Padjajaran",
    "Universitas Negeri Surabaya",
    "Institut Teknologi Sepuluh Nopember",
    "Sekolah Tinggi Meteorologi Klimatologi dan Geofisi",
    "STMIK INDONESIA BANJARMASIN",
    "Universitas Indraprasta PGRI",
    "Universitas Brawijaya",
    "universitas mataram",
    "Tadulako University ",
    "Politeknik Negeri Medan",
    "Universitas Hasanuddin",
    "Universitas Brawijaya",
    "STIKOM Cipta Karya Informatika",
    "Institut Pertanian Bogor",
    "Universitas Kristen Maranatha",
    "Telkom University",
    "Brawijaya University",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Ahmad Dahlan",
    "Universitas Airlangga",
    "universitas jendral achmad yani",
    "Universitas Syiah Kuala",
    "UNIVERSITAS JENDERAL SOEDIRMAN",
    "Universitas Riau",
    "Universitas Prof. Dr. Moestopo (Beragama)",
    "Universitas Bengkulu",
    "Universitas Sriwijaya",
    "universitas lampung",
    "Program Pascasarjana Universitas Negeri Makassar",
    "UIN Walisongo Semarang",
    "SMA Hang Tuah 5",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Indraprasta (Unindra)",
    "Sekolah Tinggi Teknologi Kedirgantaraan",
    "SMA ISLAM AL-HUSNIYAH",
    "Universitas Andalas",
    "Universitas Sriwijaya ",
    "Universitas Islam Indonesia",
    "Universitas Islam Negeri Jakarta",
    "Universitas Lampung",
    "Universitas Gunadarma",
    "Brawijaya University",
    "Politeknik Negeri Malang",
    "IAIN KENDARI",
    "Universitas Negeri Makassar",
    "Universitas Brawijaya",
    "Politeknik Elektronika Negeri Surabaya",
    "Universitas Indonesia",
    "UIN Raden Intan Lampung",
    "Universitas Veteran Bangun Nusantara Sukoharjo",
    "Cranfield University",
    "Universitas Muhammadiyah Banjarmasin",
    "Universitas Hasanuddin",
    "Universitas Negeri Medan",
    "Universitas Indonesia",
    "Institut Pertanian Bogor",
    "UIN SMH Banten",
    "Universitas Airlangga",
    "Universitas Negeri Semarang",
    "Universitas Indonesia",
    "Universitas Diponegoro",
    "Politeknik ilmu permasyarakatan",
    "Politeknik Teknologi Kimia Industri Medan",
    "Institut Pertanian Bogor",
    "UIN Sultan Maulana Hasanudin Banten",
    "Universitas Diponegoro",
    "Universitas Pendidikan Indonesia",
    "Universitas Diponegoro",
    "Universitas Bengkulu ",
    "Universitas Pendidikan Indonesia ",
    "SMA Negeri 1 Bukittinggi",
    "poltekkes siteba padang",
    "Unand",
    "Umiversitas Sriwijaya",
    "Universitas Sriwijaya",
    "Sekolah Tinggi Tarakanita",
    "Universitas Hasanuddin",
    "Tadulako University",
    "Universitas Tanjungpura",
    "Universitas Negeri Padang",
    "Teknik Sipil, Universitas Negeri Semarang",
    "SMA N 1 BERASTAGI",
    "University of Kassel and Berlin School of Economic",
    "UNIVERSITAS TADULAKO",
    "Universitas Indonesia",
    "Institut Pertanian Bogor",
    "universitas hasanuddin",
    "Institut Teknologi Bandung",
    "university 17 agustus 1945 semarang",
    "UIN Maulana Malik Ibrahim Malang",
    "Universitas Muhammadiyah Yogyakarta",
    "Universitas Komputer Indonesia",
    "Universitas Sumatera Utara",
    "Universitas Muhammadiyah Malang",
    "Universitas Diponegoro ",
    "Universitas Padjadjaran",
    "Universitas Negeri Makassar",
    "Universitas Sumatera Utara",
    "Lambung Mangkurat University",
    "universitas lampung",
    "Universitas putra Indonesia YPTK Padang",
    "Institut Pertanian Bogor",
    "Universitas Tadulako",
    "politeknik kesehatan kupang",
    "Akademi Pimpinan perusahaab",
    "Akademi Pimpinan perusahaan",
    "Universitas Lambung Mangkurat",
    "Universitas Sumatera Utara",
    "UIN Syarif Hidayatullah Jakarta",
    "universitas sebelas maret surakarta",
    "UIN walisongo Semarang",
    "Universitas Bung Hatta",
    "Universitas Padjadjaran",
    "Universitas Nusa Cendana",
    "SMAN 1 Sinjai Selatan",
    "Universitas Sumatera Utara",
    "universitas negeri padang",
    "SMA Katolik Ricci II",
    "Sekolah Tinggi Teknologi Sapta Taruna ",
    "UNIVERSITAS MATARAM",
    "Universitas Negeri Semaramg",
    "Universitas Tadulako",
    "Telkom University",
    "STEM Akamigas",
    "UNIVERSITAS DIPONEGORO",
    "Universitas Negeri Semarang",
    "UNIVERSITAS NEGERI PADANG",
    "SMA NEGERI BOSSO",
    "Universitas Muhammadiyah Yogyakarta",
    "mataram university",
    "Sosiologi FISIP Universitas Riau",
    "Institut Pertanian Bogor",
    "Institut Teknologi Sepuluh Nopember",
    "UNIVERSITAS SYIAH KUALA",
    "UIN Sunan Ampel Surabaya",
    "Universitas Indonesia",
    "Universitas Muhammadiyah Malang",
    "Brawijaya University",
    "SMA Negeri 1 Maros",
    "IAIN Purwokerto",
    "Bina Sarana Informatika",
    "Universitas Negeri Malang",
    "Universitas Sumatera Utara",
    "Universitas Negeri Malang",
    "Universitas Lambung Mangkurat",
    "SMK Kehutanan Makassar",
    "Padang State University",
    "UNJ",
    "Universitas hasanuddin",
    "Institut Teknologi Nasional",
    "Universitas Islam Indonesia",
    "Institut Pertanian Bogor",
    "Universitas Muhammadiyah Makassar",
    "universitas sriwijaya",
    "Universitas Indonesia",
    "POLTEKKES KEMENKES BENGKULU",
    "Universitas Airlangga",
    "Universitas Negeri Jakarta",
    "Telkom University",
    "Andalas University",
    "STAIN Samarinda\/IAIN Samarinda",
    "IAIN Raden Fatah Palembang",
    "Universitas Muhammadiyah Jakarta",
    "Uin Alauddin Makassar",
    "Asia Pacific University",
    "Muhammadiyah malang",
    "Universitas Indonesia",
    "Universitas Negeri Malang",
    "Andalas Univesity",
    "Universitas Negeri Yogyakarta",
    "Universitas Indonesia",
    "Universitas Indonesia",
    "Universitas Sumatera Utara",
    "Universitas Internasional Semen Indonesia",
    "Sekolah Tinggi Ilmu Statistik",
    "Universitas Sains Malaysia",
    "IAIN Syekh Nurjati Cirebon",
    "Sekolah Tinggi Teknologi Nuklir - Badan Tenaga Nuk",
    "Sekolah Tinggi Teknologi Nuklir - BATAN",
    "Universitas Muhammadiyah Malang",
    "Universitas Muhammadiyah Jakarta",
    "Universitas Gadjah Mada",
    "Universitas Bung Karno",
    "Universitas Tanjungpura",
    "Jember University",
    "universitas islam negeri sunan gunung djati bandun",
    "ITB",
    "Politeknik Negeri Sriwijaya",
    "Institut Teknologi Kalimantan (ITK)",
    "Universitas Pendidikan Indonesia",
    "Semarang State university",
    "Politeknik STMI Jakarta",
    "Universitas Negeri Malang",
    "Universitas Sebelas Maret Surakarta",
    "University's Bengkulu",
    "Birmingham University",
    "Universitas Negeri Yogyakarta",
    "Institut Agama Islam Taffaquh Fiddin Dumai",
    "UPN \"Veteran\" Jawa Timur",
    "Universitas Pendidikan Indonesia",
    "Universitas Syiah Kuala ",
    "UPN ",
    "Universitas Pendidikan Indonesia ",
    "Universitas Al Azhar Indonesia",
    "UNIVERSITAS GUNUNG RINJANI",
    "Universitas Indraprasta",
    "Universitas Negeri Semarang ",
    "SMAN 1",
    "IPDN",
    "Universitas Sumatera Utara",
    "Universitas Indonesia",
    "Universitas negeri yogyakarta",
    "Universitas negeri yogyakarta",
    "Sekolah Tinggi Pariwisata AMPTA Yogyakarta",
    "Institut Pertanian Bogor",
    "SMA N 10 PENTAGON",
    "Ssekolah Tinggi Ilmu Statistik",
    "Universitas Diponegoro",
    "Universitas Negeri Yogyakarta",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Airlangga ",
    "Universitas Airlangga",
    "UNIVERSITAS TADULAKO",
    "Airlangga University",
    "Universitas Muhammadiyah Malang",
    "Unimed",
    "Universitas Negeri Malang",
    "Institut Pertanian Bogor",
    "Poltekkes Kemenkes Bandung",
    "UIN YOGYAKARTA",
    "Sekolah Tinggi Agama Islam Muhammadiyah Sinjai",
    "UIN Syarif Hidayatullah",
    "Universitas Islam Jakarta",
    "Universitas Bengkulu",
    "sman 1 tinambung",
    "Politeknik Akademi Tekhnologi Industri Padang",
    "Universitas Negeri Makassar",
    "STIM YAPIM UNIVERSITY",
    "Universitas Airlangga",
    "Institut Teknologi Bandung",
    "SMK Muhammadiyah 2 Surabaya",
    "Universitas Riau",
    "Universitas Komputer Indonesia",
    "Universitas Indonesia",
    "SMAN 1 PRINGSEWU",
    "Universitas Islam Indonesia",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Pendidikan Indonesia",
    "Univesitas Airlangga",
    "Universitas Malikussaleh",
    "Universitas Indonesia",
    "Universitas Padjadjaran",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "Universitas Indonesia",
    "Sriwijaya University",
    "Universitas Sumatera Utara",
    "Universitas Padjadjaran",
    "Universitas Syiah Kuala",
    "Universitas Indonesia",
    "Bina Sarana Informatika",
    "Brawijaya University",
    "Universitas Indonesia",
    "Institut Pertanian Bogor",
    "Universitas Sultan Ageng Tirtayasa",
    "Mahad ali an nuaimy",
    "Universitas Balikpapan ",
    "Universitas Bengkulu",
    "Sekolah Tinggi Meteorologi Klimatologi dan Geofisi",
    "Universitas Muhammadiyah Jember",
    "Universitas Indonesia",
    "Sekolah Tinggi Ilmu Statistik",
    "Institut Pertanian Bogor",
    "Universitas Sebelas Maret",
    "Institut Teknologi Bandung",
    "Institut Pertanian Bogor",
    "Universitas Brawijaya",
    "Politeknik Negeri Lampung",
    "Universitas Pendidikan Indonesia",
    "STT-PLN",
    "UIN SUSKA RIAU",
    "Universitas Indonesia",
    "UNIVERSITAS SEBELAS MARET",
    "Universitas Indonesia",
    "Lampung University",
    "Institut Agama Islam Negeri Kendari",
    "Institut Pertanian Bogor",
    "Universitas Negeri Semarang",
    "Universitas Indonesia",
    "Universitas negeri Jakarta",
    "Institut Teknologi Nasional",
    "Universitas Islam Nahdlatul Ulama Jepara",
    "Universitas Indraprasta PGRI",
    "Universitas Pembangunan Nasional \"Veteran\" Yogyaka",
    "Universitas Pembangunan Nasional ",
    "UIN Syarif Hidayatullah Jakarta",
    "STAIN Jayapura",
    "UIN SUSKA RIAU",
    "Institut Teknologi Bandung",
    "SMA NEGERI 1 TANJUNG JABUNG TIMUR",
    "S1 Tekhnologi Informatika UNRAM",
    "Universitas Indraprasta PGRI",
    "Universitas Gadjah Mada",
    "Universitas Trunojoyo Madura",
    "Universitas Jenderal Soedirman",
    "Institut Teknologi Bandung",
    "STIKES Sumatera Utara",
    "Universitas Gadjah Mada",
    "Gadjah Mada University",
    "STIKES Sumatera Utara",
    "Sekolah tinggi ilmu kesehatan suatera utara",
    "Universitas Negeri Malang",
    "Indonesia University of Education",
    "MAN Purwokerto 2",
    "Universitas negeri semarang",
    "Sekolah tinggi ilmu kesehatan sumatera utara",
    "a4-Stikes S",
    "Universitas Gadjah Mada",
    "Stikes Sumatra Utara",
    "Institut Pertanian Bogor",
    "Institut Pertanian Bogor",
    "Institut Pertanian Bogor",
    "universitas Indonesia",
    "Politeknik Negeri Sriwijaya",
    "universitas Riau",
    "Universitas Sebelas Maret",
    "Syiah Kuala University",
    "Universitas Lambung Mangkurat",
    "Universitas Muhammadiyah Yogyakarta",
    "Halu Oleo University",
    "UIN Sunan Gunung Djati Bandung",
    "Universitas Islam Negeri Sumatera Utara",
    "Politeknik Elektronika Negeri Surabaya",
    "STIE Ahmad Dahlan",
    "Binus University",
    "Universitas Islam Negeri Alauddin Makassar",
    "Institut Pertanian Bogor",
    "UIN Sultan Maulana Hasanuddin Banten",
    "Universitas Negeri Padang",
    "Universitas indonesia",
    "Universitas Tadulako",
    "Universitas Lambung Mangkurat",
    "Universitas Padjadjaran",
    "Universitas Diponegoro",
    "Sekolah Tinggi Ilmu Kesehatan Sumatera Utara",
    "Universitas Indonesia",
    "Universitas Sriwijaya ",
    "Universitas Diponegoro",
    "Universitas Negeri Jakarta",
    "Universitas Muhammadiyah Malang",
    "jngjinirhgner",
    "Universitas Indonesia",
    "Universitas Negeri Gorontalo",
    "Universitas Sultan Ageng Tirtayasa",
    "IKIP BUDI UTOMO MALANG",
    "Institut Pertanian Bogor",
    "universitas widyatama bandung",
    "Program Studi Farmasi Universitas Islam Negeri Sya",
    "Universitas Siliwangi",
    "Universitas Muhammadiyah Malang",
    "Universitas Brawijaya",
    "Universitas Hasanuddin",
    "Universitas Pamulang",
    "Universitas Lampung",
    "esa unggul",
    " Tanjungpura University",
    "Universitas Tanjungpura",
    "Institut Pertanian Bogor",
    "Universitas Lambung Mangkurat",
    "Universitas Muhammdiyah Malang",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Pendidikan Indonesia",
    "Universitas muhammadiyah malang",
    "SMA 1 K. HULU",
    "Universitas Pendidikan Indonesia",
    "Universitas Trilogi",
    "Indonesia University Of Education",
    "Universitas Trilogi",
    "Universitas Pancasila ",
    "Institut Teknologi Bandung",
    "Airlangga University",
    "Universitas Trilogi",
    "SMA NEGERI 1 CIRUAS",
    "UNJ",
    "Institut Pertanian Bogor",
    "Universitas Sumatera Utara",
    "IPB",
    "Universitas Riau",
    "Universitas Bengkulu",
    "Institut Teknologi Del",
    "Universitas Indonesia",
    "Universitas Pendidikan Indonesia",
    "Institut Pertanian Bogor",
    "Universitas Negeri Semarang",
    "Universitas Padjadjaran ",
    "Universitas Jenderal Soedirman",
    "universitas negeri manado",
    "Universitas Negeri Yogyakarta",
    "Universitas Gadjah Mada",
    "Universitas Negeri Makassar",
    "Universitas Pakuan",
    "Universitas Pancasakti",
    "Universitas Islam 45 Bekasi",
    "Universitas Syiah Kuala",
    "Institut Pertanian Bogor",
    "Universitas Jambi",
    "Universitas Negeri Makassar",
    "Politeknik Negeri Batam",
    "Universitas Islam Negeri Maulana Malik Ibrahim Mal",
    "Universitas Trilogi",
    "Universitas Indonesia",
    "Universitas Sumatera Utara",
    "Universitas Cenderawasih",
    "Universitas Cenderawasih",
    "Umiveraitas Muhammadiyah Metro",
    "Universitas Indonesia",
    "Universitas Negeri Semarang",
    "Universitas Trilogi",
    "SEPULUH NOPEMBER INSTITUTE OF TECHNOLOGY",
    "IAIN Surakarta",
    "universitas sam ratulangi ",
    "Universitas Jember",
    "universitas samratulangi",
    "Universitas Syiah Kuala",
    "STBA Harapan",
    "SMA NEGERI 3 SURABAYA ",
    "Universitas Sumatera Utara",
    "Universitas Jambi",
    "Poltekkes Kemenkes Yogyakarta",
    "Universitas Negeri Medan",
    "Universitas Malikussaleh",
    "Institut Pertanian Bogor",
    "Universitas Muslim Indonesia Makassar",
    "Institut Teknolgi Bandung",
    "Universitas Jember",
    "Sekolah Tinggi Teknik PLN",
    "Universitas Brawijaya",
    "UNIVERSITAS JAMBI",
    "universitas pembangunan nasional veteran yogyakart",
    "Institusi kesehatan helvetia",
    "universitas sebelas maret",
    "MAN Tambakberas",
    "Universitas Indonesia",
    "Poltekkes tasikmalaya",
    "Universitas Hasanuddin",
    "Universitas Andalas",
    "ipb",
    "Universitas 17 Agutus 1945 Banyuwangi (on going)",
    "UNIVERSITAS ISLAM SULTAN AGUNG (UNISSULA)",
    "Universitas Sumatera Utara",
    "Universitas Pendidikan Indonesia",
    "Universitas Hasanuddin ",
    "POLTEKES KEMENKES RI PADANG",
    "Brawijaya University",
    "Universitas Negeri Makassar",
    "Institut Teknologi Bandung",
    "Sma Al Azhar 3 Bandar Lampung",
    "Institut Pertanian Bogor",
    "Airlangga University",
    "IPB",
    "Program Studi Farmasi Universitas Islam Negeri Sya",
    "Universitas lampung",
    "Universitas Tadulako",
    "Universitas Lambung Mangkurat",
    "UNIVERSITAS NEGERI MALANG",
    "Universitas Indonesia",
    "Universitas Sriwijaya",
    "Institut Teknologi Bandung",
    "Universitas Pertamina",
    "Islamic University Of Riau",
    "Program Studi Farmasi UIN Syarif Hidayatullah Jaka",
    "Universitas Andalas",
    "Binus Business School",
    "Universitas Indonesia",
    "STAI Madiun",
    "Universitas Padjadjaran",
    "Universitas Tidar",
    "UNIVERSITAS BRAWIJAYA",
    "UNIVERSITAS NEGERI MALANG",
    "Uny",
    "Universitas muhammadiyah bengkulu program magister",
    "Universitas Islam Negeri Alauddin Makassar",
    "Universitas Indonesia",
    "Politeknik Negeri Malang",
    "Universitas Nahdlatul Ulama Cirebon",
    "Universitas Pasundan",
    "Hasanuddin University",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "universitas lambung mangkurat",
    "Universitas Islam Negeri Antasari Banjarmasin",
    "SMAN 1 UTAN",
    "Sriwijaya University",
    "Universitas Diponegoro",
    "Institut Teknologi dan Sains Bandung",
    "Universitas Jambi",
    "Universitas Islam Negeri (UIN) Alauddin Makassar",
    "Universitas PGRI Ronggolawe",
    "Sekolah Tinggi Ilmu Kesehatan Insan Unggul Surabay",
    "Universitas Jambi",
    "Sekolah Tinggi Dirasat Islamiyah Imam Syafi'i",
    "UIN Maulana Malik Ibrahim Malang",
    "IPB ",
    "Universitas Negeri Padang",
    "Universitas Diponegoro",
    "Universitas Brawijaya",
    "POITEKNIK STTT Bandung",
    "Institut Teknologi Bandung",
    "Universitas Brawijaya",
    "Universitas Airlangga",
    "Universitas Negeri Padang",
    "State University of Medan",
    "madrasah aliyah negeri curup",
    "SMA NEGERI 3 MAROS",
    "Institut Teknologi Bandung",
    "Universitas Padjadjaran",
    "Universitas Diponegoro",
    "Universitas Negeri Padang",
    "UIN Sunan Gunung Djati Bandung",
    "Politeknik Negeri Balikpapan",
    "Universitas Terbuka",
    "Universitas Islam Negeri Alauddin Makassar",
    "Institut Teknologi Nasional Bandung",
    "Universitas Pamulang",
    "universitas Sebelas Maret",
    "institut pertanian bogor",
    "Hasanuddim University",
    "UIN Jakarta",
    "Universitas Sumatera Utara",
    "Poltekkes Kemenkes Kaltim",
    "STT Telematika Telkom Purwokerto",
    "Telkom University",
    "Institut Pertanian Bogor",
    "Universitas Indonesia",
    "University College London (Master Programme)",
    "Universitas Teknologi Yogyakarta ",
    "Institut Teknologi Bandung",
    "Universitas Muslim Maros",
    "Islamic University Of Riau",
    "Institut Pertanian Bogor",
    "Universitas trunojoyo Madura",
    "Universitas Negeri Semarang",
    "Universitas Pasundan",
    "Universitas Jember",
    "Universitas Negeri Semarang",
    "Sekolah Tinggi Ilmu Kesehatan Insan Unggul Surabay",
    "Sekolah Tinggi Ilmu Kesehatan Insan Unggul Surabay",
    "UNIVERSITAS JEMBER",
    "Universitas Brawijaya",
    "Universitas Bengkulu",
    "Universitas Negeri Surabaya",
    "Institut Pertanian Bogor",
    "Universitas Airlangga",
    "Universitas Tanjungpura",
    "Diploma IPB",
    "universitas padjajaran ",
    "Universitas Muhammadiyah Yogyakarta",
    "Universitas Jember",
    "Universitas Jenderal Soedirman",
    "Universitas Negeri Semarang",
    "Poltekkes Kemenkes RI Tasikmalaya wilayah Cirebon",
    "Jurusan Pengelolaan Terpadu Sumber Daya Alam, Seko",
    "universitas haluoleo",
    "Universitas Negeri Semarang",
    "Poltekkes kemenkes pontianak",
    "Gunadarma University",
    "universitas kader bangsa",
    "Universitas Negeri Jakarta",
    "Universitas Kader Bangsa",
    "Universitas Gunadarma",
    "universitas islam negeri sunan gunung djati bandun",
    "UNSRI",
    "Universitas Mataram",
    "Universitas Indonesia",
    "Universitas Indonesia",
    "Universitas Indonesia",
    "Universitas Muhammadiyah Yogyakarta",
    "Diponegoro University",
    "IAIN Samarinda",
    "Universitas Negeri Malang",
    "POLITEKNIK NEGERI BANJARMASIN",
    "UIN Raden Intan",
    "Syiah Kuala University",
    "Politeknik Negeri Medan ",
    "ITB",
    "Institut Teknologi Bandung",
    "Universitas Nasional ",
    "Universitas Sebelas Maret",
    "Universitas Hasanuddin",
    "SEKOLAH TINGGI ILMU STATISTIK",
    "Universitas Bengkulu",
    "UNIVERSITAS GADJAH MADA",
    "Universitas Islam Negeri Imam Bonjol Padang",
    "universitas lancang kuning",
    "Sekolah Tinggi Ekonomi Islam Tazkia",
    "Universitas Negeri Jakarta",
    "Institut Pertanian Bogor",
    "Universitas Diponegoro",
    "Universitas Islam Riau",
    "SMA N 2 Batusangkar",
    "Universitas Dharma Andalas",
    "Universitas Pendidikan Indonesia",
    "Sekolah Tinggi Teknologi Nasional Yogyakarta",
    "Universitas Islam Negeri Maulana Malik Ibrahim Mal",
    "Politeknik Negeri Padang ",
    "PEM Akamigas Cepu",
    "Universitas Muslim Indonesia ",
    "Sekolah tinggi farmasi indonesia yayasan perintis ",
    "Universitas Padjadjaran",
    "Universitas 17 Agustus 1945 Surabaya",
    "Institut Teknologi Sepuluh Nopember",
    "MA Alliful Ikhwan SAA",
    "unniversitas hasanuddin ",
    "Pakuan University ",
    "Universitas Negeri padang",
    "UIN AR RANIRY",
    "STIE Dewantara",
    "Universitas Internasional Batam",
    "Universitas Mataram",
    "Universitas Jenderal Soedirman",
    "Institut Teknologi Sepuluh Nopember ",
    "Andalas university",
    "Universitas Padjadjaran",
    "Universitas andalas",
    "Universitas Sumatera Utara ",
    "Universitas Islam Negeri Sumatera Utara",
    "Universitas Pendidikan Indonesia",
    "Harvard University",
    "Universitas Mulawarman",
    "Universitas Sriwijaya",
    "Teknologi Informasi Universitas Sumatera Utara",
    "Sultan Agung Islamic University",
    "Universitas Indonesia",
    "Universitas Indonesia",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Teknologi Yogyakarta",
    "Hasanuddin University",
    "UIN Walisongo Semarang",
    "Universitas Negeri Semarang",
    "Universitas PGRI Madiun",
    "Universitas Padjadjaran",
    "UIN Jakarta",
    "Institut Agama Islam Negeri Ponorogo",
    "Sekolah Tinggi Ilmu Ekonomi Nasional Banjarmasin",
    "Universitas Pendidikan Indonesia",
    "Sekolah Tinggi Ilmu Statistik",
    "Universitas Andalas ",
    "Pondok Pesantren Puteri Ummul Mukminin",
    "UNP",
    "Universitas Indonesia",
    "Universitas Widyatama",
    "universitas malikussaleh",
    "Lampung University",
    "Universitas Sumatera Utara",
    "Universitas Brawijaya",
    "STMIK TRIGUNA DHARMA MEDAN",
    "STMIK Nusa Mandiri",
    "Jurusan PTSDA Pascasarjana UNAND",
    "Universitas Islam Indonesia",
    "Politeknik Negeri Sriwijaya",
    "Universitas Indonesia (2016-sekarang)",
    "Politeknik Negeri Jakarta",
    "Institut Teknologi Bandung",
    "Universitas Indonesia",
    "Universitas Andalas",
    "Universitas Pakuan",
    "SMA",
    "Universitas Jenderal Achmad Yani (UNJANI)",
    "Tanjungpura university",
    "SEKOLAH TINGGI ILMU KESEHATAN PANAKKUKANG MAKASSAR",
    "Mas Proyek Univa Medan",
    "Diponegoro University",
    "UNIVERSITAS SUMATERA UTARA",
    "Universitas Sumatera Utara",
    "Sekolah Tinggi Hukum Indonesia Jentera",
    "Sma negeri 7 sijunjung",
    "Universitas Gadjah Mada",
    "Universitas maarif hasyim latief",
    "Universitar Pancasakti Tegal",
    "Universitas Mulawarman 2014",
    "Universitas Sriwijaya",
    "Universitas Pendidikan Indonesia ",
    "Indonesia University of Education",
    "Universitas Sriwijaya",
    "Universitas Hasanuddin",
    "Politeknik Harapan Bersama",
    "Institut Pertanian Bogor",
    "Universitas Negeri Padang",
    "Universitas Padjadjaran",
    "Universitas Pendidikan Indonesia",
    "cyber Business of indonesia",
    "Universitas syiah kuala",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Negeri Medan",
    "Universitas Indonesia (2016-sekarang)",
    "Sekolah Tinggi Teknik PLN Jakarta",
    "Universitas Mataram",
    "Universitas Pendidikan Indonesia ",
    "Universitas Sumatera Utara",
    "Institut Pertanian Bogor",
    "sman 1 labuhan deli",
    "Universitas Sebelas Maret Surakarta ",
    "Universitas Bengkulu",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Pendidikan Indonesia",
    "Tohoku University",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "Universitas Mercubuana",
    "Sebelas Maret University",
    "Universitas Hasanuddin",
    "Institut Teknologi Sepuluh Nopember",
    "Bina Sarana Informatika",
    "UNIVERSITAS ANDALAS",
    "Universitas Sebelas Maret Surakarta",
    "IAIN Surakarta",
    "Universitas Tadulako",
    "Sekolah Tinggi Ilmu Ekonomi Manajemen Bisnis STEMB",
    "UNDIP",
    "Universitas Ichsan",
    "FK UNAIR ",
    "Universitas Padjadjaran",
    "UGM ",
    "STKIP Surya",
    "Universitas Sebelas Maret",
    "Universitas Brawijaya",
    "Institut Agama Islam Negeri Surakarta",
    "Universitas Padjadjaran",
    "Universitas Sumatera Utara",
    "Padjadjaran University",
    "Institut Pemerintahan Dalam Negeri",
    "Politeknik STMI Jakarta",
    "Universitas Negeri Jakarta",
    "Stikes",
    "UIN Imam Bonjol Padang",
    "Universitas Negeri Semarang",
    "Universitas Panca Marga Probolinggo",
    "STIE Ahmad Dahlan Jakarta",
    "Brawijaya University",
    "STIKES mercubaktijaya Padang",
    "Universitas Sumatera Utara",
    "Sekolah Tinggi Ilmu Statistik",
    "STIM LPI MAKASSAR UNIVERSITY",
    "SMA\/MA",
    "Mulawarman University",
    "Universitas Lambung Mangkurat Banjarmasin",
    "Diploma Administrasi Bisnis",
    "Universitas Riau",
    "StikesSU",
    "Universitas Negeri Medan",
    "Universitas Sulawesi Barat",
    "Universitas Mulawarman",
    "Universitas Syiah Kuala ",
    "USU",
    "Universitas Islam Sultan Agung (Unissula)  Semaran",
    "Universitas Brawijaya",
    "UIN Sunan Kalijaga Yogyakarta",
    "IAIN Purwokerto",
    "Universitas Ahmad Dahlan",
    "universitas komputer indonesia",
    "Udayana University",
    "Universitas Gadjah Mada",
    "Universitas Negeri Makassar",
    "Universitas Lambung Mangkurat",
    "Universitas Pendidikan Indonesia",
    "akademi audiologi Indonesia FK UI RSCM",
    "Universitas Sumatera Utara",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Bengkulu",
    "man 8",
    "Universitas Negeri Medan",
    "Politeknik negeri medan",
    "Universitas Winaya Mukti",
    "STAIN Pekalongan",
    "Universitas Negeri Jakarta",
    "Universitas Negeri Medan",
    "University of Sumatra Utara",
    "Universitas Negeri Jakarta",
    "Universitas Darussalam",
    "Universitas Andalas ",
    "Universitas Negeri Surabaya",
    "universitas andalas",
    "Brawijaya University",
    "Universitas Negeri Padang",
    "Universitas Pendidikan Indonesia Bandung",
    "PTKI Medan",
    "Universitas Kanjuruhan",
    "sekolah tinggi teknik pln",
    "UIN Antasari",
    "Universitas Negeri Sriwijaya",
    "Andalas University",
    "Universitas Negeri Malang ",
    "Sekolah Tinggi Meteorologi Klimatologi dan Geofisi",
    "Universitas Sriwijaya",
    "Institut Pertanian Bogor",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Gadjah Mada",
    "Universitas Negeri Makassar",
    "Universitas Islam Negeri Walisongo Semarang",
    "Universitas Indonesia",
    "Magister Epidemiologi Universitas Diponegoro",
    "Undana",
    "Institut Pertanian Bogor",
    "Universitas Brawijaya",
    "Institut Sains dan Teknologi Nasional",
    "Universitas Sumatera Utara",
    "Institut Pertanian Bogor",
    "Universitas Muhammadiyah Bandung ",
    "Institut Pertanian Bogor",
    "Universitas Pakuan",
    "Universitas Padjadjaran",
    "universitas muhammadiyah surakarta ",
    "Universitas Winaya Mukti",
    "UIN Syarif Hidayatullah Jakarta",
    "IIB Darmajaya",
    "Universitas Padjadjaran",
    "Universitas Negeri Jakarta",
    "Sekolah Tinggi Ilmu Statistik",
    "Institut Pertanian Bogor",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Indonesia",
    "Universitas Indonesia",
    "Universitas Gadjah Mada",
    "Sebelas Maret Surakarta University",
    "Universitas Brawijaya",
    "Universitas Andalas",
    "Universitas Padjadjaran",
    "Universitas Islam Jakarta",
    "Sekolah Tinggi Teknik PLN Jakarta",
    "Universitas Pembangunan Nasional Veteran Jakarta ",
    "Universitas Pendidikan Indonesi",
    "universitas Pandanaran",
    "Universitas Islam Indonesia",
    "Nusa Cendana University",
    "Universitas Timor",
    "UIN Jakarta",
    "SMA SMART Ekselensia Indonesia",
    "SMAN 1 KUARO",
    "UIN Maulana Malik Ibrahim Malang",
    "UIN Jakarta",
    "Universitas Pendidikan Indonesia ",
    "Universitas Sumatera Utara",
    "Universitas Sebelas Maret",
    "UIN IB PADANG",
    "Universitas Veteran Bangun Nusantara",
    "Institut Ilmu Sosial dan Ilmu Politik (IISIP) ",
    "International Islamic University Malaysia",
    "Universitas Riau",
    "International Islamic University Malaysia",
    "Universitas Hasanuddin ",
    "Universitas Gadjah Mada",
    "UIN Jakarta",
    "Universitas Indonesia",
    "Institut Teknologi Bandung",
    "BINUS University",
    "UIN Jakarta",
    "Universitas Islam Negeri Syarif Hidayatullah Jakar",
    "Universitas Tadulako",
    "Universitas Islam Negeri Syarif Hidayatullah Jakar",
    "Universitas Islam Negeri Syarif Hidayatullah Jakar",
    "Universitas Islam Negeri Syarif Hidayatullah Jakar",
    "Universitas Islam Negeri Syarif Hidayatullah Jakar",
    "STID DI Al-Hikmah",
    "PENS",
    "Politeknik LP3I Kramat Raya",
    "Universitas Negeri Semarang",
    "Universitas Halu Oleo",
    "Universitas Islam Jakarta",
    "Universitas Indonesia",
    "Universitas Indonesia",
    "Universitas Lambung Mangkurat",
    "universitas Pamulang",
    "Institut Teknologi Bandung",
    "Universitas Lambung Mangkurat",
    "Universitas Pamulang",
    "Universitas Diponegoro",
    "institut teknologi sumatera",
    "Institut Pertanian Bogor",
    "SMAN 1 KARANGANYAR KEBUMEN ",
    "Universitas Negeri Jakarta",
    "UNJANI",
    "Universitas Sriwijaya",
    "Universitas Lambung Mangkurat",
    "Universitas Hasanuddin",
    "UNIVERSITAS ISLAM NEGERI SULTAN SYARIF KASIM RIAU",
    "ESQ Business School",
    "Universitas Negeri Malang",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Sebelas Maret",
    "Universitas Negeri Padang ",
    "Institut Teknologi Bandung",
    "Universitas Bengkulu",
    "Medan State University",
    "sman 1 ranah pesisir",
    "SMK Telkom",
    "atarbiyyah",
    "Universitas Negeri Gorontalo",
    "Universitas Sriwijaya",
    "Politeknik Kesehatan Kemenkes Makassar",
    "universitas bengkulu",
    "Universitas Andalas",
    "Universitas Syiah Kuala",
    "Universitas Negeri Jakarta",
    "Politeknik Elektronika Negeri Surabaya",
    "Universitas Muhammadiyah Malang",
    "Universitas Islam Indonesia",
    "Universitas Muhammadiyah Malang",
    "Bogor Agricultural University ",
    "Universitas Negeri Medan",
    "Universitas Padjadjaran",
    "Universitas Pendidikan Indonesia",
    "Universitas Negeri Jakarta",
    "Universitas Lambung Mangkurat",
    "UIN ANTASARI BANJARMASIN",
    "Universitas Negeri Makassar",
    "Universitas Pattimura",
    "Politeknik Negeri Ujung Pandang",
    "Universitas Negeri Semarang",
    "Sekolah Tinggi Ilmu Statistik",
    "Universitas Padjadjaran",
    "Uin Suska Riau",
    "Universitas Negeri Jakarta",
    "Universitas Garut",
    "Universitas Negeri Jakarta",
    "PTKI Medan",
    "Universitas Sriwijaya",
    "Universitas Negeri Semarang (UNNES)",
    "Institut Teknologi Bandung",
    "universitas negeri semarang",
    "Universitas Bengkulu",
    "SMKN 13",
    "Universitas Indonesia",
    "SMP 13",
    "SMP 11",
    "SMK Nusa Bangsa",
    "SMKN 29",
    "Universitas Islam Negri Sunan Kalijaga",
    "Institut Pertanian Bogor",
    "Universitas Sriwijaya",
    "Universitas Islam Negeri Syarif Hidaytullah Jakart",
    "Universitas Gunadarma",
    "Universitas Islam Negeri Syarif Hidaytullah Jakart",
    "Universitas Islam Negeri Jakarta Syarif Hidayatull",
    "Universitas Islam Negeri Jakarta Syarif Hidayatull",
    "Sekolah Tinggi Akuntansi Negara",
    "Universitas Udayana",
    "Universitas Riau",
    "Universitas Diponegoro",
    "SMAN 1 Jombang",
    "Institut Teknologi Bandung",
    "Universitas Negeri Jakarta ",
    "Institut Pertanian Bogor ",
    "SMAN 1 TALAGA",
    "Universitas Padjadjaran",
    "Universitas Sebelas Maret",
    "Sekolah Tinggi Ilmu Kesehatan Sumatera Utara",
    "Universitas Negeri Makassar",
    "Universitas Gadjah Mada",
    "Universitas Indonesia ",
    "Universitas Gadjah Mada",
    "Telling University",
    "Universitas Indonesia",
    "Universitas Brawijaya",
    "Universitas Padjadjaran",
    "Universitas Andalas ",
    "Universitas Negeri Jenderal Soedirman",
    "Universitas Pendidikan Indonesia",
    "UIN BANDUNG",
    "Universitas Syiah Kuala",
    "UIN Antasari Banjarmasin",
    "Poltekkes Kemenkes Yogyakarta",
    "Jember University",
    "Akademi Kesehatan Lingkungan Pemerintah Provinsi S",
    "Akademi Kesehatan Lingkungan Pemerintah Provinsi S",
    "Universitas Borneo Tarakan",
    "Institut Pertanian Bogor",
    "Universitas Riau",
    "Universitas Lambung Mangkurat",
    "Universitas Negeri Makassar",
    "Universitas Hasanuddin",
    "Universitas siliwangi",
    "Universitas Lambung Mangkurat",
    "Universitas Negeri Makassar",
    "Universitas Sumatera Utara",
    "Universitas Indonesia",
    "University College London",
    "UIN ALAUDDIN MAKASSAR",
    "Universitas Brawijaya",
    "UIN AR RANIRY",
    "Institut Teknologi Bandung",
    "Politeknik Negeri Lhokseumawe",
    "Universitas Diponegoro",
    "Universitas Airlangga",
    "UIN Syarif Hidayatullah Jakarta",
    "Institut Teknologi Sepuluh Nopember Surabaya",
    "Universitas Islam Jakarta",
    "Universitas Sangga Buana YPKP Bandung",
    "Sekolah Tinggi Meteorologi Klimatologi dan Geofisi",
    "STMKG",
    "UNIVERSITAS JAMBI",
    "Institut Pertanian Bogor",
    "Sekolah Tinggi Ilmu Statistik",
    "Universitas Indonesia",
    "Universitas Brawijaya",
    "STIKES Sumatera Utara",
    "UNIVERSITAS ANDALAS",
    "UIN Syarif Hidayatullah Jakarta",
    "Institut Teknologi Sepuluh Nopember Surabaya",
    "Sekolah Tinggi Ilmu Kesehatan Sumatera Utara",
    "Universitas Jember",
    "INSTITUT TEKNOLOGI BANDUNG",
    "Universitas Gadjah Mada",
    "Universitas Andalas",
    "Universitas Dian Nuswantoro",
    "Universitas Negeri Medan",
    "Universitas Bengkulu",
    "Insitut Pertanian Bogor",
    "INSTITUT TEKNOLOGI SEPULUH NOPEMBER",
    "Universitas Malikussaleh",
    "Universitas Malikussaleh",
    "UIN Syarif Hidayatullah",
    "Universitas Sebelas Maret Surakarta",
    "Universitas Negeri Surabaya",
    "Politeknik STMI Jakarta",
    "Universitas Indonesia",
    "Universitas Pendidikan Indonesia",
    "Institut Teknologi Bandung",
    "Universitas Negeri Semarang",
    "UNIVERSITAS GADJAH MADA",
    "STKIP Garut",
    "Universitas Diponegoro",
    "Universitas riau",
    "Universitas Negeri Medan",
    "UIN Antasari Banjarmasin",
    "Universitas Andalas",
    "Universitas Terbuka Banjarmasin",
    "Universitas Lambung Mangkurat",
    "Universitas Indonesia",
    "Universitas Negeri Semarang",
    "Universitas Negeri Semarang",
    "Universitas Lambung Mangkurat",
    "Universitas Negeri Jakarta",
    "Universitas Bung Hatta",
    "Universitas Brawijaya ",
    "Universitas Brawijaya",
    "Universitas Islam Negeri Alauddin Makassar",
    "Politeknik Negeri Ujung Pandang",
    "Universitas Islam Sultan Agung",
    "Teknik Lingkungan Universitas Brawijaya",
    "Universitas Gadjah Mada",
    "Universitas Muhammadiyah Makassar",
    "Institut Teknologi Sepuluh Nopember ",
    "Universitas Teknologi Sumbawa",
    "Universitas Sebelas Maret Surakarta",
    "Institut Pertanian Bogor",
    "Universitas Brawijaya",
    "universitas islam negeri sunan gunung djati bandun",
    "Universitas Islam Negeri Syarif Hidayatullah Jakar",
    "upn jatim",
    "Prodi Psikologi, Universitas Lambung Mangkurat",
    "Universitas Malikussaleh",
    "INSTITUT TEKNOLOGI SEPULUH NOPEMBER ",
    "Universitas Padjadjaran",
    "UNIVERSITAS BRAWIJAYA",
    "Sekolah Tinggi Ilmu Islam dan Bahasa Arab",
    "universitas islam negeri sunan gunung djati bandun",
    "UIN BANDUNG",
    "Politeknik Negeri Malang",
    "Universitas Negri Jakarta",
    "Universitas Islam Indonesia",
    "Universitas Sumatera Utara",
    "Universitas Diponegoro",
    "Institut Teknologi Sepuluh Nopember",
    "UIN BANDUNG",
    "Uin suska riau ",
    "UNIVERSITAS INDONESIA",
    "Institut Teknologi Bandung",
    "Universitas Sulawesi Barat",
    "SMAIT IQRA Bengkulu ",
    "Universitas Sulawesi Barat",
    "Universitas Terbuka",
    "Institut Teknologi Adhi Tama Surabaya",
    "Mander Portman Woodward School",
    "Hasanuddin University",
    "universitas negeri malang",
    "Universitas Negeri Semarang",
    "Universitas Negeri Padang",
    "STMIK Sumedang",
    "Universitas Jambi",
    "Universitas Riau",
    "Mercu Buana University",
    "Universitas Pendidikan Indonesia",
    "Universitas Trisakti",
    "Universitas Diponegoro",
    "Insititut Pertanian Bogor",
    "Universitas Islam Negeri Antasari Banjarmasin",
    "ekonomi syariah universitas mulawarman",
    "Universitas Medan Area",
    "Unuversitas Brawijaya",
    "Institut Pertanian Bogor",
    "Universitas Muhammadiyah Tapanuli Selatan",
    "Sekolah tinggi ilmu kesehatan sumatera utara",
    "Stiu Al-Hikmah",
    "Universitas Diponegoro",
    "Universitas Terbuka",
    "Universitas Mulawarman",
    "Madrasah Aliyah Negeri 2 Tulungagung",
    "Universitas Muhammadiyah Surabaya",
    "Universitas Gadjah Mada",
    "Politeknik Negeri Jakarta",
    "universitas nusa endana",
    "UIN ANTASARI BANJARMASIN",
    "Institut Pemerintahan Dalam Negeri ",
    "Universitas Bosowa Makassar",
    "Universitas Sumatera Utara",
    "Universitas Syiah Kuala",
    "Universitas Pendidikan Indonesia",
    "Universitas Negeri Padang",
    "Universitas Brawijaya",
    "Universitas Papua",
    "universitas WR Supratman",
    "UNJ",
    "Universitas Pertamina ",
    "Universitas Islam Riau",
    "Darussalam University Gontor",
    "Universitas Indonesia",
    "Universitas Indonesia",
    "Universitas Airlangga",
    "Stikes 'aisyiyah yogyakarta",
    "Universitas Lambung Mangkurat",
    "Universitas Islam Negeri Antasari Banjarmasin",
    "Institut Agama Islam Negeri (Ambon)",
    "Universitas Muhammadiyah Riau",
    "BINUS University",
    "Univeritas Riau",
    "Institut Teknologi Bandung",
    "Universitas Gadjah Mada",
    "Universitas Halu Oleo",
    "Universitas Pendidikan Indonesia ",
    "Universitas Pendidikan Indonesia ",
    "Universitas Airlangga",
    "Universitas Muhammadiyah Jakarta",
    "SMA Negeri 1 Belitang",
    "Universitas Indonesia",
    "Universitas Andalas",
    "Universitas Negeri Medan",
    "Universitas Padjadjaran",
    "Kedokteran Hewan UGM",
    "Universitas Diponegoro",
    "Universitas Lampung",
    "Unpad",
    "Universitas Negeri Medan",
    "Universitas Gunadarma",
    "Universitas Bengkulu",
    "Universitas Indonesia",
    "Universitas Gadjah Mada",
    "Universitas Sriwijaya",
    "Universitas Negeri Makassar",
    "Universitas Indonesia",
    "Universitas Tanjungpura",
    "Universitas Negeri Makassar",
    "Universitas Lancang Kuning",
    "Akademi Manajemen Informatika dan Komputer Taruna",
    "President University ",
    "Diploma 3 teknik kimia unsyiah",
    "UIN Antasari Banjarmasin",
    "Universitas Diponegoro",
    "Universitas Brawijaya",
    "Gunadarma University",
    "Universitas Islam Negeri Sulthan Thaha Saifuddin J",
    "Institut Pertanian Bogor",
    "Universitas Baturaja",
    "Universitas Gadjah Mada",
    "Universitas Islam Negeri Lampung",
    "Universitas Sriwijya",
    "King Mongkut's University of Technology Thonburi (",
    "Universitas Negeri Padang",
    "Universitas Brawijaya",
    "Institut Teknologi dan Sains Bandung",
    "Universitas Indonesia ",
    "Universitas Ciputra",
    "Universitas Negeri Malang",
    "Politeknik Negeri Medan",
    "Universitas Padjadjaran",
    "Universitas Gadjah Mada",
    "Unnes",
    "UIN Imam Bonjol Padang",
    "Paramadina University",
    "Universitas Hasanuddin",
    "Universitas Pendidikan Indonesia ",
    "Universitas Sultan Ageng Tirtayasa",
    "Universitas Syiah Kuala",
    "Islamic university of sultan agung",
    "Politeknik Negeri Jakarta",
    "SMA Negeri 2 Sijunjung",
    "Universitas Padjadjaran",
    "Padjadjaran University",
    "Universitas Padjadjaran",
    "Universitas Negeri Semarang",
    "Universitas Sebelas Maret Surakarta",
    "Universitas Tadulako",
    "Universitas Negeri Jakarta 2012-2016",
    "Universitas Respati Indonesia",
    "Universitas Padjadjaran",
    "Universitas Indonesia",
    "Nanyang Technological University",
    "Sekolah Tinggi Ilmu Statistik (STIS)",
    "Institut Teknologi Bandung",
    "Telkom University Bandung",
    "Institut Teknologi Bandung",
    "Universitas Hasanuddin",
    "Smk ibu pertiwi 2",
    "Universitas Gadjah Mada",
    "Universitas Gadjah Mada",
    "Universitas Islam Negeri Arraniry",
    "SMAS SUKMA BANGSA LHOKSEUMAWE",
    "Universitas Indonesia",
    "Universitas Negeri Malang",
    "Diponegoro University ",
    "Universitas Indonesia",
    "Universitas Diponegoro",
    "Universitas Diponegoro",
    "Akademi Kesehatan Lingkungan Pemprov Sumsel",
    "Institut Pertanian Bogor",
    "Universitas Sumatera Utara",
    "Universitas Diponegoro",
    "Universitas Internasional Batam",
    "Sekolah Tinggi Ilmu Statistik (Kedinasan)",
    "Universitas Syiah Kuala",
    "Universitas Malikussaleh",
    "Institut Teknologi Bandung",
    "Universitas Malikussaleh",
    "Diploma III",
    "Universitas Muhammadiyah Magelang",
    "universitas diponegoro",
    "Universitas Pendidikan Indonesia",
    "Universitas Islam Negeri Antasari Banjarmasin",
    "Universitas Negeri Jakarta ",
    "Agribisnis Fakultas Pertanian",
    "Universitas Brawijaya",
    "universitas sam ratulangi manado",
    "Universitas Gadjah Mada",
    "Universitas Andalas",
    "Universitas Andalas",
    "STIKes-Sumatera Utara",
    "Universitas Diponegoro",
    "Universitas Indonesia",
    "universitas sriwijaya",
    "STKS BANDUNG",
    "Universitas Diponegoro",
    "Universitas Andalas Padang",
    "Brawijaya University",
    "Universitas Islam Kalimantan Muhammad Arsyad Al Ba",
    "Universitas Negeri Padang",
    "Universitas Indraprasta PGRI",
    "Universitas Diponegoro",
    "Universitas Gadjah Mada",
    "Universitas Diponegoro",
    "Universitas Tama Jagakarsa",
    "Universitas Negeri Yogyakarta",
    "UIN SUNAN GUNUNG DJATI BANDUNG",
    "UIN Syarif Hidayatullah Jakarta",
    "Universitas Islam Negeri Ar-Raniry Banda Aceh",
    "UIN Syarif Hidayatullah Jakarta 2015 dan Kahfi BBC",
    "Universitas Negeri Padang",
    "UIN Syarif Hidayatullah Jakarta 2015 dan Kahfi BBC",
    "Universitas Mulawarman",
    "UIN Jakarta",
    "Universitas Hasanuddin",
    "Universitas Muhammadiyah Makassar",
    "Universitas Pendidikan Indonesia",
    "UIN Raden Fatah Palembang",
    "Universitas Hasanuddin",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "Universitas Padjadjaran",
    "Universitas Gadjah Mada",
    "Politeknik pertanian universitas Andalas",
    "Universitas Sebelas Maret",
    "Universitas Pendidikan Indonesia",
    "UIN Antasari",
    "universitas islam negri bandung",
    "UIN Sunan Gunung Djati Bandung",
    "universitas andalas",
    "Institut Sains dan Teknologi Indonesia",
    "Andalas University",
    "KAHFI BBC Motivator",
    "Universitas Brawijaya",
    "Universitas Gadjah Mada",
    "Universitas Jenderal Soedirman ",
    "Universitas Gadjah Mada",
    "uksw",
    "Syiah Kuala University",
    "Universitas Sebelas Maret",
    "Universitas Muhammadiyah Yogyakarta",
    "SMA ISLAM AZ ZAHRAH PALEMBANG",
    "Universitas Gadjah Mada",
    "Politeknik Keuangan Negara STAN",
    "UNIVERSITAS NEGERI MALANG",
    "Universitas islam negeri sultan syarif qasim riau",
    "Universitas Muhammadiyah Yogyakarta",
    "Universitas Muhammadiyah Surabaya",
    "Universitas Indonesia",
    "Universitas Syiah Kuala ",
    "Sriwijaya University",
    "Institut Agama Islam Negeri Bukittinggi",
    "Universitas Negeri Jakarta",
    "Universitas Negeri Padang",
    "Bina Nusantara University",
    "Universitas Jember",
    "Universitas Pendidikan Indonesia",
    "Universitas Negeri Jakarta",
    "National Pingtung University of Science and Techno",
    "Telkom University",
    "institut pertanian bogor ",
    "Universitas Gadjah Mada",
    "Institut Agama Islam Negeri Jember",
    "Asian Institute of Technology Thailand (Magister)",
    "Telkom University",
    "Universitas Negeri Jakarta",
    "Univeritas Bosowa",
    "Universitas Tama Jagakarsa",
    "asdsad",
    "Universitas Sumatera Utara",
    "Universitas Sriwijaya",
    "Institut Pertanian Bogor",
    "Universitas Indonesia",
    "Politeknik Elektronika Negeri Surabaya",
    "Universitas Islam Negeri Alauddin Makassar",
    "Universitas Jenderal Soedirman",
    "Institut Pertanian Bogor",
    "Sekolah Tinggi Ilmu Ekonomi (STIE) Syariah Bengkal",
    "STIT darul fatah",
    "Universitas Diponegoro",
    "Universitas Diponegoro",
    "Univeristy of Melbourne - Melbourne Business Schoo",
    "Pondok Pesantren Darul Muttaqien, Bogor ",
    "Universitas Hasanuddin",
    "Stei sebi",
    "Universitas Lampung",
    "Universitas Indonesia",
    "Institut Teknologi Sepuluh Nopember Surabaya",
    "Universitas Pendidikan Indonesia",
    "Universitas Gadjah Mada",
    "Universitas Andalas",
    "Universitas Riau",
    "Satya Wacana Christian University",
    "Universitas Syiah Kuala",
    "Universitas Negeri Medan",
    "UNIVERSITAS ANDALAS",
    "Telkom University",
    "SMAN 3 CIAMIS",
    "Universitas Malikussaleh",
    "Institut Pertanian Bogor ",
    "Universitas Sriwijaya",
    "Universitas pebangunan nasional",
    "Universitas pembangunan nasional \"Veteran\" Jawa Ti",
    "Universitas pembangunan nasional ",
    "Universitas Negeri Medan ",
    "Universitas Jambi",
    "Institut Pertanian Bogor",
    "Universitas Pendidikan Indonesia",
    "Diponegoro University",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Negeri Malang",
    "institut teknologi sepuluh nopember surabaya",
    "Universitas Sumatera Utara (USU)",
    "Universitas Tujuh Belas Agustus Semarang",
    "Universitas Indonesia",
    "University Of Lampung ",
    "Poltekkes Kemenkes Makassar",
    "Universitas Indonesia",
    "Universitas Sebelas Maret",
    "Institut Pertanian Bogor",
    "UIN Raden Fatah Palembang",
    "UIN Imam Bonjol Padang",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "Institut Pertanian Bogor",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "Universitas Malikussaleh",
    "Universitas sumatera utara",
    "Universitas Pendidikan Indonesia",
    "Universitas Islam Negeri Antasari Banjarmasin",
    "Universitas Islam Negeri Sunan Gunung Djati Bandun",
    "SMAN 1 TUALANG",
    "Universitas Islam Negeri Walisongo",
    "Universitas Bangka Belitung",
    "Institut Teknologi Telkom",
    "Universitas Pendidikan Indonesia",
    "Universitas Indonesia",
    "Universitas Brawijaya",
    "Diploma Tiga Gizi Poltekkes Kemenkes Gorontalo",
    "Universitas Negeri Malang",
    "Universitas Tadulako",
    "Universitas Brawijaya",
    "Universitas Diponegoro",
    "Stei sebi",
    "Universitas Islam Bandung",
    "Universitas Negeri Semarang",
    "Universitas Muhammadiyah Yogyakarta",
    "UIN SYARIF HIDAYATULLAH",
    "Universitas Bengkulu",
    "Bogor Agricultural University",
    "Riau University",
    "Universitas Lambung Mangkurat",
    "Universitas Riau",
    "politeknik negeri batam",
    "Universitas Diponegoro",
    "Institut Teknologi Bandung",
    "Universitas Sriwijaya",
    "Sekolah Tinggi Meteorologi Klimatologi dan Geofisika",
    "STKIP AISYIYAH RIAU",
    "Universitas Trunojoyo Madura",
    "Universitas Banten Jaya",
    "Palangka Raya University",
    "Sekolah TInggi Multi Media MMTC Yogyakarta",
    "Politeknik Elektronika Negeri Surabaya",
    "Universitas Syiah Kuala",
    "ITB (Institut Teknologi Bandung)",
    "Trisakti University",
    "Universitas Islam Negeri Syarif Hidayatullah Jakarta",
    "ESQ Business School",
    "Universitas gadjah mada",
    "Sekolah Tinggi Ilmu Statistik (STIS)",
    "Universitas Nusa Cendana Kupang",
    "sma",
    "Universitas Diponegoro",
    "Institut Teknologi Sumatera",
    "Syiah Kuala University",
    "universitas terbuka",
    "Universitas Diponegoro",
    "Universitas Negeri Jakarta",
    "Universitas Pancasila",
    "Universitas Halu Oleo2",
    "ESQ Business School",
    "Universitas Negeri Semarang",
    "Universitas Negeri Semarang",
    "lampung university",
    "Universitas Muslim Indonesia",
    "Syiah Kuala University",
    "Universitas Sultan Ageng Tirtayasa",
    "Universittas Gadjah Mada",
    "Universutas Syiah Kuala",
    "Universitas Airlangga",
    "Institut Teknologi Sepuluh Nopember",
    "IPB",
    "Universitas Tadulako",
    "Universitas Sriwijaya",
    "Universitas Riau",
    "Institut Teknologi Nasional Malang",
    "Universitas Pancasila",
    "Bogor Agricultural University ",
    "Universitas Andalas",
    "Politeknik Negeri Pontianak",
    "Universitas Islam Sultan Agung Semarang",
    "Universitas Negeri Makassar (UNM)",
    "Universitas Negeri Medan",
    "Jurusan  Ilmu Kelautan Fakultas Perikanan dan Kelautan Universitas Riau",
    "Institut Pertanian Bogor",
    "Ilmu Ekonomi Universitas Negeri Padang",
    "Pascasarjana Universitas Negeri Malang",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Palangka Raya",
    "Institut Teknologi Bandung",
    "Universitas Padjadjaran",
    "Universitas Sriwijaya",
    "Universitas Indonesia",
    "UIN Syarif Hidayatullah Jakarta",
    "IPB",
    "Universitas Negeri Padang",
    "Universitas Negeri Padang",
    "Universitas Bengkulu",
    "Institut Teknologi Bandung",
    "Universitas Islam Negeri Syarif Hidayatullah Jakarta",
    "UNIVERSITAS MULAWARMAN",
    "Universitas Lambung Mangkurat Banjarmasin",
    "Universitas Negeri Medan",
    "Universitas Muria Kudus",
    "Universitas Lampung",
    "PKN STAN",
    "Sekolah Tinggi Energi dan Mineral (STEM Akamigas)",
    "S-1 Pendidikan Matematika Universitas Pendidikan Indonesia (UPI) Bandung",
    "Universitas Trisakti",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Airlangga",
    "Universitas Sebelas Maret",
    "politeknik negeri lampung",
    "UIN Sunan Ampel Surabaya",
    "Universitas Pendidikan Indonesia (UPI) Bandung",
    "Universitas Islam Riau",
    "STAI-PIQ Sumbar",
    "UGM",
    "Universitas Sultan Ageng Tirtayasa",
    "Universitas Hasanuddin",
    "Universitas Lampung",
    "UPN Veteran Yogyakarta",
    "Universitas Andalas",
    "Universitas Sriwijaya ",
    "Institut Pertanian Bogor",
    "Universitas Indonesia",
    "Universitas Brawijaya",
    "MA.  Patra Mandiri ",
    "Universitas telkom",
    "Universitas Brawijaya",
    "Universitas Pattimura",
    "Universitas Indonesia",
    "Universitas Islam Sultan Agung Semarang",
    "Universitas Sulawesi Barat",
    "Sriwijaya University",
    "Universitas Islam Indonesia ",
    "Universitas Gadjah Mada",
    "Sriwijaya University",
    "Institut Teknologi Sepuluh Nopember",
    "universitas riau",
    "Universitas Sebelas Maret",
    "Universitas Padjadjaran",
    "Universitas Mataram",
    "Universitas Riau",
    "Airlangga University",
    "Sultan Agung Islamic University",
    "Universitas Jambi",
    "UNIVERSITAS TADULAKO",
    "Universitas Sumatera Utara",
    "Universitas Padjadjaran",
    "Universitas Negeri Malang",
    "universitas islam negeri sunan gunung djati bandung",
    "Universitas Andalas",
    "Universitas Islam Negri Sultan Thaha Saifuddin Jambi",
    "Universitas Siliwangi",
    "UIN Syarif Hidayatullah Jakarta",
    "STMKG",
    "Sriwijaya University",
    "Universitas Pebangunan Nasional Veteran Jakarta",
    "Universitas",
    "Universitas Paramadina",
    "Sriwijaya University",
    "Sriwijaya University",
    "UNIVERSITAS NEGERI JAKARTA",
    "Sriwijaya University",
    "Universitas Jember",
    "Universitas Indonesia",
    "UNIVERSITAS TERBUKA MAJENE",
    "Universitas Sriwijaya",
    "Politeknik Negeri Medan",
    "Universitas Islam Indonesia",
    "Universitas Islam Negeri Sultan Syarif Kasi Riau",
    "Universitas Indonesia",
    "Universitas Jenderal Soedirman",
    "Universitas Negeri Yogyakarta ",
    "Universitas Lampung",
    "universitas Airlangga",
    "UIN Walisongo Semarang",
    "Universitas Muhammadiyah Surakarta",
    "Institut Pertanian Bogor",
    "Universitas Gadjah Mada",
    "UNIVERSITAS NEGERI MEDAN",
    "Uin Sunan Gunung Djati Bandung",
    "Institut Teknologi Bandung",
    "Universitas Airlangga",
    "Universitas Diponegoro",
    "Universitas Brawijaya",
    "Institut Teknologi Sepuluh Nopember",
    "Muhammadiyah Malang University",
    "universitas lambung mangkurat fmipa",
    "Universitas Tadulako",
    "Universitas Negeri Malang",
    "Universitas Negeri Padang",
    "Universitas Negeri Semarang ",
    "Universitas Sulawesi Barat",
    "Universitas Airlangga",
    "Kampus Iisip Tercinta",
    "Universitas Airlangga",
    "Universitas Islam 45 Bekasi",
    "Institut Teknologi Bandung",
    "Universitas Sumatera Utara ",
    "Universitas Jenderal Soedirman",
    "Universitas Gadjah Mada",
    "Universitas Padjadjaran",
    "Universitas Lambung Mangkurat Banjarmasin",
    "Universitas Indonesia",
    "UIN Raden Intan Lampung",
    "SEKOLAH TINGGI TEKNIK-PLN",
    "universitas negeri padang",
    "UNIVERSITAS NEGERI MEDAN",
    "Universitas Muhammadiyah Surakarta",
    "UNIVERSITAS PENDIDIKAN INDONESIA",
    "Universitas Sumatera Utara",
    "jember university",
    "STT PLN",
    "Universitas Muhammadiyah Malang",
    "STEI SEBI",
    "Institut Teknologi Bandung",
    "Universitas Gadjah Mada",
    "telkom universitas",
    "Universitas Siliwangi",
    "Universitas Indonesia",
    "Universitas Airlangga",
    "STEI SEBI",
    "Univ. Muhammadiyah Malang",
    "Universitas Padjadjaran",
    "Universitas Indonesia",
    "Universitas Lambung Mangkurat",
    "Telkom University",
    "Brawijaya University",
    "UIN sunan gunung Djati Bandung",
    "Universitas Syiah Kuala",
    "Universitas Andalas",
    "Universitas Gadjah Mada",
    "Universitas Bengkulu",
    "Universitas Diponegoro",
    "STIKES \u2018Aisyiyah Bandung",
    "Politeknik Keuangan Negara STAN",
    "Universitas UIN Syarief Hidayatullah Jakarta",
    "Institut Teknologi Bandung",
    "Universitas Sriwijaya",
    "Universitas Mataram ",
    "Universitas Gadjah Mada",
    "Kampus kehidupan",
    "Universitas Lambung Mangkurat",
    "Universitas Lampung",
    "Universitas Sam Ratulangi Manado",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Lampung",
    "Universitas Negeri Padang",
    "Universitas Islam Negeri Syarif Hidayatullah Jakarta",
    "Universitas al-azhar indonesia ",
    "Universitas Negeri Medan",
    "SMA Negeri 1 Limboto",
    "Tanjungpura University",
    "Padjadjaran University",
    "Politeknik Keuangan Negara STAN",
    "SMA N 1 wuryantoro",
    "Sekolah Tinggi Energi dan Mineral (STEM) Akamigas",
    "Universitas Indonesia",
    "Universitas Hasanuddin ",
    "Universitas Mahammadiyah Tangerang",
    "Universitas Mataram",
    "universitas udayana",
    "Universitas Pendidikan Indonesia",
    "Sekolah Tinggi Ilmu Statistik",
    "Universitas Diponegoro",
    "Universitas Negeri Semarang",
    "Universitas Syiah Kuala",
    "Universitas Negeri Makassar",
    "Universitas Syiah Kuala",
    "Universitas merdeka malang",
    "Universitas Brawijaya",
    "Universitas Gadjah Mada",
    "Institut Teknologi Bandung",
    "Universitas tadulako",
    "Universitas Brawijaya",
    "Universitas Hasanuddin",
    "IPB",
    "Universitas Diponegoro",
    "Universotas Negeri Malang",
    "Universitas Negeri Malang",
    "Pondok Pesantren Darul Arqam Muhammadiyah Garut",
    "Sekolah Tinggi Ilmu Statistik",
    "UPN \"Veteran\" Yogyakarta",
    "Muhammadiyah Surakarta University",
    "UIN Sultan Syarif Kasim Riau",
    "Universitas Diponegoro - Fisip",
    "Universitas Airlangga",
    "Universitas Negeri Semarang",
    "Universitas Muhammadiyah Malang",
    "Institut Teknologi Bandung",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Negeri Malang",
    "Institut Teknologi Sepuluh Nopember",
    "Tidak Ada",
    "Politeknik Keungan Negara STAN",
    "universitas pattimura",
    "Andalas University",
    "Universitas Riau",
    "Politeknik Piksi Ganesha",
    "Institut Teknologi Sepuluh Nopember",
    "PPM School of Management ",
    "Malikussaleh University",
    "Universitas Andalas",
    "Politeknik STMI",
    "Universitas Teknokrat Indonesia",
    "Telkom University",
    "Universitas Airlangga",
    "Universitas Trunojoyo Madura",
    "Institut Koperasi Indonesia",
    "UIN Alauddin Makassar",
    "Universitas Komputer Indonesia",
    "Institut Teknologi Bandung",
    "s1 pendidikan dokter FK UB 2011-2015, S1 Profesi Dokter 2015-2017, S2 Biomedik (Dual Degree) 2015-se",
    "Universitas Brawijaya Kampus III (Kediri)",
    "Trisakti University",
    "Jenderal Soedirman University",
    "Universitas Padjadjaran",
    "Universitas negeri makassar ",
    "Universitas Hasanuddin",
    "PROSIA School of Communication",
    "Universitas Indonesia",
    "Institut Teknologi Bandung",
    "Universitas Padjadjaran",
    "Universitas Jember",
    "Universitas Indonesia",
    "Universitas Muhammadiyah Malang",
    "Universitas Negeri Medan",
    "Politeknik Negeri Lampung",
    "Universitas Indonesia",
    "Universitas Kristen Satya Wacana",
    "UIN AR RANIRY",
    "Universitas Negeri Jakarta",
    "Universitas Mulawarman",
    "Universitas Diponegoro",
    "Lampung University",
    "Institut Teknologi Bandung",
    "universitas sumatera utara",
    "Universitas Negeri Padang",
    "Airlangga University",
    "Universitas Negeri Medan",
    "Politekik Kesehatan Kemenkes Palembang",
    "Universitas Bengkulu",
    "Universitas Suryakancana ",
    "Universitas Sriwijaya",
    "Universitas Gadjah Mada",
    "Institut Pertanian Bogor",
    "Universitas Nusa Cendana",
    "Universitas Negeri Padang",
    "Universitas Indonesia",
    "Universitas Negeri Medan",
    "UIN AR RANIRY",
    "Institut Teknologi Bandung",
    "Politeknik Kesehatan Kemenkes Palembang",
    "Universitas Sriwijaya",
    "Universitas Andalas",
    "Universitas Brawijaya",
    "Universitas Jambi",
    "Institut Teknologi Bandung",
    "Institut Koperasi Indonesia",
    "UIN SUNAN GUNUNG DJATI BANDUNG",
    "UIN Antasari",
    "President University ",
    "Universitas Islam Negeri Sunan Gunung Djati Bandung",
    "Institut Teknologi Bandung",
    "Universitas Hasanuddin",
    "Universitas Brawijaya Malang",
    "Universitas Diponegoro",
    "Universitas Sebelas Maret",
    "Universitas Negeri Malang",
    "Universitas Diponegoro",
    "Universitas Indonesia",
    "SMA",
    "Universitas Padjadjaran (2014-2018)",
    "Institut Teknologi Bandung",
    "Fakultas Keperawatan Universitas Syiah Kuala",
    "SMA Taman Siswa Cabang Pematang Siantar",
    "Universitas Hasanuddin",
    "Universitas Diponegoro",
    "Universitas Lambung Mangkurat",
    "National Chiao Tung University Taiwan",
    "Institut Pertanian Bogor",
    "Institut Teknologi Bandung",
    "Universitas Tanjungpura",
    "UNIVERSITAS MUHAMMADIYAH PALEMBANG",
    "Program Studi Farmasi UIN Syarif Hidayatullah Jakarta",
    "Universitas Padjadjaran",
    "Universitas Mulawarman",
    "Universitas Negeri Jakarta",
    "Universitas Bengkulu",
    "Universitas Negeri Semarang",
    "Universitas Syiah Kuala",
    "Gadjah Mada University",
    "Universitas Brawijaya",
    "Institut Pertanian Bogor",
    "Universitas Airlangga",
    "SMA Negri 1 Stabat",
    "Universitas Syiah Kuala",
    "Program Studi Televisi Film Fakultas Ilmu Budaya Universitas Jember",
    "Universitas Padjadjaran",
    "Universitas Indonesia",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Diponegoro",
    "Universitas Sumatera Utara",
    "Universitas Hasanuddin",
    "Institut Teknologi Nasional Bandung ",
    "Universitas Indonesia",
    "STBA JIA Bekasi",
    "Universitas Al Azhar Indonesia",
    "Universitas Padjadjaran",
    "Sekolah Tinggi Ilmu Statistik",
    "Institut Pertanian Bogor",
    "UNIVERSITAS BENGKULU",
    "ITENAS",
    "dsdwd",
    "Universitas Negeri Medan",
    "Universitas Negeri Malang",
    "UIN SUSKA RIAU",
    "Institut Teknologi Bandung",
    "Universitas Padjadjaran",
    "SMK Negeri 1 Tebinh Tinggi",
    "Telkom University",
    "Universitas Malikussaleh",
    "Universitas Semarang",
    "Universitas Padjadjaran",
    "SMAN 3 Medan",
    "Universitas Gadjah Mada",
    "Universitas Islam Negri Syarif Hidayatullah Jakarta",
    "Institut Teknologi Bandung",
    "Fakultas Kesehatan Masyarakat Universitas Muhammadiyah Aceh",
    "Stikes Al Irsyad Cilacap",
    "Sekolah Tinggi Kesejahteraan Sosial",
    "Universitas Sumatera Utara",
    "UIN Syarif hidayatullah Jakarta",
    "Universitas Tadulako",
    "Poltekkes Aceh",
    "SMA Unggul Negeri 08 Palembamg",
    "Institut Pertanian Bogor",
    "Attahiriyah University",
    "UPN \"Veteran\" Yogyakarta",
    "Universitas Negeri Jakarta",
    "Universitas Muhammadiyah Malang",
    "Universitas Sumatera Utara",
    "UIN Walisongo semarang",
    "Universitas Indonesia",
    "Universitas Sebelas Maret",
    "Universitas Mulawarman Samarinda",
    "Universitas Tanjunpura",
    "Universitas Diponegoro",
    "Universitas Padjadjaran",
    "Universitas Negeri Malang",
    "Sekolah Tinggi Manajemen Industri",
    "Universitas Islam Bandung",
    "IPDN (INSTITUT PEMERINTAHAN DALAM NEGERI)",
    "Universitas Brawijaya",
    "Universitas Sumatera Utara ",
    "Universitas Negeri Semarang",
    "smk farmasi bip majene",
    "Institut Sains dan Teknologi Nasional",
    "Universitas Negeri Makassar",
    "STKIP Kusuma Negara Jakarta",
    "Sekolah Tinggi Ilmu Statistik",
    "Young Entrepreneur Academy Indonesia",
    "Universitas Pamulang",
    "Universitas Negeri Yogyakarta ",
    "Universitas Gadjah Mada",
    "Institut Pertanian Bogor ",
    "Akademi Keperawatan Jayakarta",
    "STEI SEBI",
    "Universitas Diponegoro",
    "Universitas Pendidikan Indonesia",
    "Universitas Andalas",
    "Universitas Halu Oleo",
    "Universitas Padjadjaran",
    "Sekolah Tinggi Perikanan",
    "STIE MULIA PRATAMA",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Negeri Medan",
    "Sekolah Tinggi Teknik PLN Jakarta",
    "Universitas Negeri Medan",
    "Universitas Nasional Jakarta",
    "Universitas Gadjah Mada",
    "Universitas Gadjah Mada",
    "Universitas Tomakaka Mamuju",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Riau",
    "Universitas Jember",
    "UIN Sunan Ampel Surabaya",
    "Universitas Pendidikan Indonesia ",
    "its surabaya",
    "Universitas Gunadarma",
    "Universitas gadjah mada",
    "IPB",
    "Universitas Indonesia",
    "Universitas Negeri Padang",
    "UNiversitas Brawijaya",
    "Universitas Hasanuddin",
    "STEI SEBI",
    "Universitas Negeri Yogyakarta",
]

export default listKampus
